import NavbarSec from "@/Components/Common/Navbar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Tea",
  description: "Generated by create next app",
};

const CommonLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <NavbarSec />
      {children}
    </div>
  );
};

export default CommonLayout;
